
[[headers]]
  for = "/assets/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200